// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantMenu.Data;

#nullable disable

namespace RestaurantMenu.Migrations
{
    [DbContext(typeof(MenuContext))]
    partial class MenuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RestaurantMenu.Models.Dish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://www.abeautifulplate.com/wp-content/uploads/2015/08/the-best-homemade-margherita-pizza-1-4.jpg",
                            Name = "Margheritta",
                            Price = 7.5
                        });
                });

            modelBuilder.Entity("RestaurantMenu.Models.DishIngridient", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("IngridientId")
                        .HasColumnType("int");

                    b.HasKey("DishId", "IngridientId");

                    b.HasIndex("IngridientId");

                    b.ToTable("DishIngridients");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            IngridientId = 1
                        },
                        new
                        {
                            DishId = 1,
                            IngridientId = 2
                        },
                        new
                        {
                            DishId = 1,
                            IngridientId = 3
                        });
                });

            modelBuilder.Entity("RestaurantMenu.Models.Ingridient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ingridients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mozarella"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Tomato Passata"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bazil"
                        });
                });

            modelBuilder.Entity("RestaurantMenu.Models.DishIngridient", b =>
                {
                    b.HasOne("RestaurantMenu.Models.Dish", "Dish")
                        .WithMany("DishIngridient")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantMenu.Models.Ingridient", "Ingridient")
                        .WithMany("DishIngridient")
                        .HasForeignKey("IngridientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Ingridient");
                });

            modelBuilder.Entity("RestaurantMenu.Models.Dish", b =>
                {
                    b.Navigation("DishIngridient");
                });

            modelBuilder.Entity("RestaurantMenu.Models.Ingridient", b =>
                {
                    b.Navigation("DishIngridient");
                });
#pragma warning restore 612, 618
        }
    }
}
